# Generated by Django 3.0.1 on 2020-08-09 16:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appOne', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Destination',
            new_name='Registrationform',
        ),
    ]
