# Generated by Django 3.0.1 on 2020-02-28 18:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('DEMOAPP', '0004_remove_allcourses_startedfrom'),
    ]

    operations = [
        migrations.AddField(
            model_name='allcourses',
            name='startedfrom',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 28, 18, 18, 52, 896481, tzinfo=utc), verbose_name='Started from'),
            preserve_default=False,
        ),
    ]
